### ISSUE TITLE
Error during install : fatal: le chemin de destination '/home/yunohost.app/kresus' existe déjà et n'est pas un répertoire vide

### ISSUE THREAD

**Issue by palchr** [scith/kresus_ynh#1]
In the Install the script , during the "sudo git clone https://framagit.org/bnjbvr/kresus.git /home/yunohost.app/kresus" the system raise an issue regarding the fact that the folder is not empty and thus launch the Remove script. Install fail .

**Comment by scith** [comment]
Hello, the package does not work yet sorry. I use this repo for test but it is not to be used for other purposes yet sorry

**Comment by palchr** [comment]
Understand ... 
Anyway feel free to assk if you have some need in testing .

**Comment by palchr** [comment]
Understand ... 
Anyway feel free to assk if you have some need in testing .

**Comment by scith** [comment]
Thanks :) I don't have time to further improve this package yet, but it was promising! If I remember correctly I had problems with the reverse proxy (among other things)

**Comment by palchr** [comment]
Don't know if this help but there is some discussion around the standalone use of Kresus here : https://www.karolak.fr/blog/2016/03/18/kresus-un-gestionnaire-web-de-finances-personnelles-libre  and setup under nginx here : https://framabin.org/?f1807f0ec3cbd772#CLimWUIvohuIly9h1I/DiIXoAtYfoIVgfeqKPSIoMLU

**Comment by scith** [comment]
Thanks, these are the instructions I followed yes. I think I managed to install Kresus but not to run it as a service yet.
Feel free to contribute if you wish :) I don't have time to investigate now but I could join you later. I am really interested in this package
